name: Docker PostGIS CI

on:
  push:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
  schedule:
    - cron: '15 5 * * 2'  # Weekly, 1 day after the upstream

# Cancel existing executions when new commits are pushed onto the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:

    strategy:
      fail-fast: false
      matrix:
        # exclude the latest version set for use with "include" below
        postgres: [13, 14, 15, 16, 17]
        postgis: ['3.5']
        latest: [false]
        include:
        - postgres: 18  # only use the single latest version with "latest: true"
          postgis: '3.6'
          latest: true

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}

    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write
      packages: write

    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:

    - name: Set up QEMU for amd64 and arm64
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

    - name: Set up Depot CLI
      uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
      with:
        images: ghcr.io/${{ github.repository_owner }}/postgis
        labels: |
          org.opencontainers.image.title=postgis
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.base.name=docker.io/postgis/postgis:${{ env.VERSION }}
        tags: |
          type=raw,value=${{ env.VERSION }},enable=true,priority=200
          type=raw,value=${{ matrix.postgres }},enable=true,priority=200
          type=raw,value=latest,enable=${{ matrix.latest }},priority=200

    - name: Login to GitHub Container Registry
      if: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Multi-platform build without push
      if: ${{ !((github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT) }}
      uses: depot/build-push-action@9785b135c3c76c33db102e45be96a25ab55cd507
      with:
        project: p4q8k8mb22
        platforms: linux/amd64,linux/arm64
        context: https://github.com/postgis/docker-postgis.git#master
        file: ${{ env.VERSION }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: false

    - name: Multi-platform build and push
      if: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}
      uses: depot/build-push-action@9785b135c3c76c33db102e45be96a25ab55cd507
      with:
        project: p4q8k8mb22
        no-cache: true
        platforms: linux/amd64,linux/arm64
        context: https://github.com/postgis/docker-postgis.git#master
        file: ${{ env.VERSION }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: true
