name: Docker PostGIS CI

on:
  push:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
  schedule:
    - cron: '15 5 * * 2'  # Weekly, 1 day after the upstream

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:

    strategy:
      matrix:
        # list compatible with arm64; exclude the latest version set for use with "include" below
        postgres: [11, 12, 13, 14]
        postgis: ['3.3']
        latest: [false]
        include:
        - postgres: 15  # only use the single latest version with "latest: true"
          postgis: '3.3'
          latest: true

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}

    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:

    - name: Depot
      uses: depot/setup-action@ad05a752b7f61b7a0b2d19d8b02b4da9d9c761a3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
      with:
        images: ghcr.io/${{ github.repository_owner }}/postgis
        labels: |
          org.opencontainers.image.title=postgis
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.base.name=docker.io/postgis/postgis:${{ env.VERSION }}
        tags: |
          type=raw,value=${{ env.VERSION }},enable=true,priority=200
          type=raw,value=${{ matrix.postgres }},enable=true,priority=200
          type=raw,value=latest,enable=${{ matrix.latest }},priority=200

    - name: Login to GitHub Container Registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}

    - name: Multi-platform build and push
      uses: depot/build-push-action@70cb220542e03ae2296b19d65e56cf3fc078b637
      with:
        project: p4q8k8mb22
        platforms: linux/amd64,linux/arm64
        context: github.com/postgis/docker-postgis#master
        file: ${{ env.VERSION }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}
