name: Docker PostGIS CI

on:
  push:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
  schedule:
    - cron: '15 5 * * 2'  # Weekly, 1 day after the upstream

# Cancel existing executions when new commits are pushed onto the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:

    strategy:
      matrix:
        # exclude the latest version set for use with "include" below
        postgres: [12, 13, 14, 15]
        postgis: ['3.4']
        latest: [false]
        include:
        - postgres: 16  # only use the single latest version with "latest: true"
          postgis: '3.4'
          latest: true

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}

    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write
      packages: write

    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:

    - name: Set up QEMU for amd64 and arm64
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

    - name: Set up Depot CLI
      uses: depot/setup-action@eb2efd6287c794d456be5e1a7963fa8772c39ce5

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
      with:
        images: ghcr.io/${{ github.repository_owner }}/postgis
        labels: |
          org.opencontainers.image.title=postgis
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.base.name=docker.io/postgis/postgis:${{ env.VERSION }}
        tags: |
          type=raw,value=${{ env.VERSION }},enable=true,priority=200
          type=raw,value=${{ matrix.postgres }},enable=true,priority=200
          type=raw,value=latest,enable=${{ matrix.latest }},priority=200

    - name: Login to GitHub Container Registry
      if: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Multi-platform build (docker buildx)
      if: ${{ !((github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT) }}
      uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1
      with:
        platforms: linux/amd64,linux/arm64
        context: https://github.com/postgis/docker-postgis.git#master
        file: ${{ env.VERSION }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: false

    - name: Multi-platform build and push (depot.dev)
      if: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}
      uses: depot/build-push-action@e7743ee6585d261968c7ae0ef64977ee98c09d74
      with:
        project: p4q8k8mb22
        no-cache: true
        platforms: linux/amd64,linux/arm64
        context: https://github.com/postgis/docker-postgis.git#master
        file: ${{ env.VERSION }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: true
