name: Docker PostGIS CI

on:
  push:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
  schedule:
    - cron: '15 5 * * 2'  # Weekly, 1 day after the upstream

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:

    strategy:
      matrix:
        # list compatible with arm64; exclude the latest version set for use with "include" below
        postgres: [11, 12, 13]
        postgis: ['3.3']
        latest: [false]
        include:
        - postgres: 10  # 3.3 is not available for PG 10
          postgis: '3.2'
          latest: false
        - postgres: 14  # only use the single latest version with "latest: true"
          postgis: '3.3'
          latest: true

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}

    runs-on: ubuntu-20.04

    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:

    - name: Set up QEMU for amd64 and arm64
      uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
      with:
        images: ghcr.io/${{ github.repository_owner }}/postgis
        labels: |
          org.opencontainers.image.title=postgis
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.base.name=docker.io/postgis/postgis:${{ env.VERSION }}
        tags: |
          type=raw,value=${{ env.VERSION }},enable=true,priority=200
          type=raw,value=latest,enable=${{ matrix.latest }},priority=200

    - name: Login to GitHub Container Registry
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}

    - name: Multi-platform build and push
      uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
      with:
        platforms: linux/amd64,linux/arm64
        context: github.com/postgis/docker-postgis#master
        file: ${{ env.VERSION }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: ${{ (github.ref == 'refs/heads/multiarch') && (github.event_name != 'pull_request') && !env.ACT }}
